openapi: 3.2.0
info:
  title: ALTR Management Plan API
  version: 12.25.1
  description: Welcome to the Swagger documentation for ALTR's Management API (MAPI).
  termsOfService: https://www.altr.com/info/altr-solutions-inc-terms-of-service
  contact:
    name: Support
    email: support@altr.com
servers:
- url: https://altrnet.live.altr.com/api
  description: ALTR Management API
security:
- basicAuth: []
tags:
- name: Plan
  description: Operations related to the features the organization has
paths:
  /plan:
    get:
      tags:
      - Plan
      summary: Returns a list features the organization has access to
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      features:
                        $ref: '#/components/schemas/Features'
                  success:
                    type: boolean
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
      operationId: getPlan
      x-operation-id-source: derived
  /plan/upgrade:
    patch:
      tags:
      - Plan
      summary: Upgrades the organization to Enterprise, but only if they are in free tier
      description: This endpoint is only accessible via ALTR's UI; it cannot be accessed from an API key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - activeDataUsers
              - streetAddressLine1
              - state
              - zip
              - tier
              properties:
                zip:
                  type: integer
                  example: 20500
                state:
                  type: string
                  example: DC
                streetAddressLine1:
                  type: string
                  example: 1600 Pennsylvania Avenue NW
                streetAddressLine2:
                  type: string
                  example: 1600 Pennsylvania Avenue NW
                activeDataUsers:
                  type: integer
                  example: 10
                tier:
                  type: integer
                  default: 2
                  description: The tier version you are going too. Must be two and will always be set to two
      responses:
        '200':
          $ref: '#/components/responses/OkResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
      operationId: patchPlanUpgrade
      x-operation-id-source: derived
  /plan/contact:
    post:
      tags:
      - Plan
      summary: Sends a request to upgrade to Enterprise Plus
      description: This endpoint is only accessible via ALTR's UI; it cannot be accessed from an API key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: I would like to upgrade to Enterprise Plus
      responses:
        '200':
          $ref: '#/components/responses/OkResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
      operationId: postPlanContact
      x-operation-id-source: derived
components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          examples:
            default:
              value:
                data:
                  message: '''id'' must be present'
                  statusCode: 400
                  date: '2022-07-20T18:00:58.723Z'
                success: false
            with context property:
              value:
                data:
                  message: Invalid credentials.
                  statusCode: 400
                  context:
                    error_code: 60000
                    title: DB_CONNECTION
                  date: '2022-07-20T18:00:58.723Z'
                success: false
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          example:
            data:
              message: Resource is forbidden
              statusCode: 403
              date: '2022-07-20T18:00:58.723Z'
            success: false
    OkResponse:
      description: Indicates that the process was successful in being retrieved/sent. Does not necessarily mean that it will complete.
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
              success:
                type: boolean
                example: true
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          example:
            data:
              message: Unauthorized
              statusCode: 401
              date: '2022-07-20T18:00:58.723Z'
            success: false
    InternalError:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          example:
            data:
              message: Internal Server Error
              statusCode: 500
              date: '2022-07-20T18:00:58.723Z'
            success: false
  schemas:
    Features:
      type: object
      properties:
        feat_dashboard:
          type: boolean
        feat_anomalies:
          type: boolean
        feat_intelligence:
          type: boolean
        feat_dataPolicy:
          type: boolean
        feat_unlimitedLockColumnRelationship:
          type: boolean
        feat_lockColumnLimit:
          type: integer
          example: 10
        feat_systemConfiguration:
          type: boolean
        feat_databaseDrivers:
          type: boolean
          example: false
        feat_tokenization:
          type: boolean
        feat_tokenizationAPI:
          type: boolean
        feat_managementAPI:
          type: boolean
        feat_s3Integration:
          type: boolean
        feat_auditLogs:
          type: boolean
        feat_settings:
          type: boolean
        feat_tags:
          type: boolean
        feat_rowaccess:
          type: boolean
        feat_databaseLimit:
          type: integer
          example: 1
    ApiError:
      type: object
      properties:
        data:
          type: object
          properties:
            message:
              type: string
              example: Internal Server Error
            statusCode:
              type: integer
              example: 500
            context:
              type: object
              example: {}
              description: An object with properties that may **optionally** appear, will contain more information relating to the error message.
            date:
              type: string
              format: date-time
        success:
          type: boolean
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: MAPI uses [HTTP Basic Authentication](https://swagger.io/docs/specification/authentication/basic-authentication/).<br/><br/>MAPI credentials can be obtained on the [API page](https://altrnet.live.altr.com/settings/preferences/api) (found under Settings > Preferences > API) of ALTR's portal for Enterprise and Enterprise+ customers.<br/><br/>Usernames are the 'Key Names' listed on that page, and Passwords are the 'Key Secret' provided when an API key is created.
externalDocs:
  description: ALTR Documentation
  url: https://docs.altr.com/
